export interface TeamMember {
  name: string
  role: string
  initials: string
  slug: string
  bio: string
  skills: string[]
  email: string
  github?: string
  linkedin?: string
}

export const teamMembers: TeamMember[] = [
  {
    name: "Ana García",
    role: "Frontend Developer",
    initials: "AG",
    slug: "ana-garcia",
    bio: "Especialista en React y Vue.js con pasión por crear interfaces de usuario intuitivas y accesibles. Me encanta trabajar en proyectos que impacten positivamente a los usuarios.",
    skills: ["React", "Vue.js", "TypeScript", "Tailwind CSS", "Responsive Design"],
    email: "ana.garcia@webcolaborativa.com",
    github: "https://github.com/anagarcia",
    linkedin: "https://linkedin.com/in/anagarcia",
  },
  {
    name: "Carlos Ruiz",
    role: "Backend Developer",
    initials: "CR",
    slug: "carlos-ruiz",
    bio: "Desarrollador backend con experiencia en Node.js y bases de datos. Me apasiona crear APIs robustas y escalables.",
    skills: ["Node.js", "Express", "PostgreSQL", "MongoDB", "REST APIs"],
    email: "carlos.ruiz@webcolaborativa.com",
    github: "https://github.com/carlosruiz",
  },
  {
    name: "María López",
    role: "UI/UX Designer",
    initials: "ML",
    slug: "maria-lopez",
    bio: "Diseñadora enfocada en crear experiencias de usuario memorables. Combino creatividad con investigación para diseñar soluciones centradas en el usuario.",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping", "Design Systems"],
    email: "maria.lopez@webcolaborativa.com",
  },
  {
    name: "Juan Pérez",
    role: "Full Stack Developer",
    initials: "JP",
    slug: "juan-perez",
    bio: "Desarrollador full stack con experiencia en tecnologías modernas. Me gusta resolver problemas complejos y aprender nuevas tecnologías.",
    skills: ["Next.js", "React", "Node.js", "TypeScript", "Docker"],
    email: "juan.perez@webcolaborativa.com",
    github: "https://github.com/juanperez",
  },
  {
    name: "Laura Martínez",
    role: "Project Manager",
    initials: "LM",
    slug: "laura-martinez",
    bio: "Project Manager certificada en metodologías ágiles. Me especializo en coordinar equipos y asegurar la entrega exitosa de proyectos.",
    skills: ["Scrum", "Agile", "Jira", "Team Leadership", "Risk Management"],
    email: "laura.martinez@webcolaborativa.com",
    linkedin: "https://linkedin.com/in/lauramartinez",
  },
  {
    name: "Diego Torres",
    role: "DevOps Engineer",
    initials: "DT",
    slug: "diego-torres",
    bio: "Ingeniero DevOps especializado en automatización y CI/CD. Me apasiona optimizar procesos y mejorar la eficiencia del desarrollo.",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD", "Terraform"],
    email: "diego.torres@webcolaborativa.com",
    github: "https://github.com/diegotorres",
  },
  {
    name: "Sofia Ramírez",
    role: "QA Tester",
    initials: "SR",
    slug: "sofia-ramirez",
    bio: "Especialista en aseguramiento de calidad con ojo para los detalles. Me dedico a garantizar que cada producto cumpla con los más altos estándares.",
    skills: ["Manual Testing", "Automated Testing", "Selenium", "Jest", "Test Planning"],
    email: "sofia.ramirez@webcolaborativa.com",
  },
  {
    name: "Miguel Ángel",
    role: "Database Admin",
    initials: "MA",
    slug: "miguel-angel",
    bio: "Administrador de bases de datos con experiencia en optimización y seguridad. Me especializo en diseñar esquemas eficientes y escalables.",
    skills: ["PostgreSQL", "MySQL", "MongoDB", "Database Design", "Performance Tuning"],
    email: "miguel.angel@webcolaborativa.com",
  },
  {
    name: "Elena Vargas",
    role: "Frontend Developer",
    initials: "EV",
    slug: "elena-vargas",
    bio: "Desarrolladora frontend apasionada por las animaciones y las micro-interacciones. Me encanta dar vida a los diseños.",
    skills: ["JavaScript", "React", "CSS Animations", "GSAP", "Three.js"],
    email: "elena.vargas@webcolaborativa.com",
    github: "https://github.com/elenavargas",
  },
  {
    name: "Roberto Silva",
    role: "Backend Developer",
    initials: "RS",
    slug: "roberto-silva",
    bio: "Desarrollador backend enfocado en arquitecturas escalables y microservicios. Me gusta trabajar con tecnologías de vanguardia.",
    skills: ["Python", "Django", "FastAPI", "Redis", "Microservices"],
    email: "roberto.silva@webcolaborativa.com",
    github: "https://github.com/robertosilva",
  },
  {
    name: "Patricia Gómez",
    role: "UI/UX Designer",
    initials: "PG",
    slug: "patricia-gomez",
    bio: "Diseñadora UI/UX con enfoque en accesibilidad y diseño inclusivo. Creo experiencias que todos puedan disfrutar.",
    skills: ["Sketch", "Figma", "Accessibility", "User Testing", "Wireframing"],
    email: "patricia.gomez@webcolaborativa.com",
    linkedin: "https://linkedin.com/in/patriciagomez",
  },
  {
    name: "Fernando Castro",
    role: "Full Stack Developer",
    initials: "FC",
    slug: "fernando-castro",
    bio: "Desarrollador full stack con pasión por el código limpio y las mejores prácticas. Me especializo en crear aplicaciones web modernas.",
    skills: ["Vue.js", "Nuxt.js", "Node.js", "GraphQL", "Testing"],
    email: "fernando.castro@webcolaborativa.com",
    github: "https://github.com/fernandocastro",
  },
  {
    name: "Isabel Moreno",
    role: "Scrum Master",
    initials: "IM",
    slug: "isabel-moreno",
    bio: "Scrum Master certificada con experiencia en facilitar equipos ágiles. Me dedico a eliminar impedimentos y fomentar la colaboración.",
    skills: ["Scrum", "Kanban", "Facilitation", "Coaching", "Conflict Resolution"],
    email: "isabel.moreno@webcolaborativa.com",
    linkedin: "https://linkedin.com/in/isabelmoreno",
  },
  {
    name: "Andrés Jiménez",
    role: "Security Specialist",
    initials: "AJ",
    slug: "andres-jimenez",
    bio: "Especialista en seguridad informática enfocado en proteger aplicaciones web. Me apasiona encontrar y solucionar vulnerabilidades.",
    skills: ["Security Auditing", "Penetration Testing", "OWASP", "Encryption", "Compliance"],
    email: "andres.jimenez@webcolaborativa.com",
    github: "https://github.com/andresjimenez",
  },
]
